"""Selenium headless Chrome screenshot taker for Grafana panels."""

import io
import time
from typing import Any

from PIL import Image, ImageDraw, ImageFont
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from webdriver_manager.chrome import ChromeDriverManager


# ---------------------------------------------------------------------------
# Driver lifecycle
# ---------------------------------------------------------------------------

def get_driver() -> webdriver.Chrome:
    """Create and return a headless Chrome WebDriver at 1280x800.

    Uses webdriver-manager to automatically download the matching ChromeDriver.
    """
    opts = Options()
    opts.add_argument("--headless=new")
    opts.add_argument("--no-sandbox")
    opts.add_argument("--disable-dev-shm-usage")
    opts.add_argument("--disable-gpu")
    opts.add_argument("--window-size=1280,800")
    opts.add_argument("--disable-extensions")
    opts.add_argument("--log-level=3")

    service = Service(ChromeDriverManager().install())
    return webdriver.Chrome(service=service, options=opts)


# ---------------------------------------------------------------------------
# Login
# ---------------------------------------------------------------------------

def login(
    driver: webdriver.Chrome,
    base_url: str,
    username: str,
    password: str,
    timeout: int = 15,
) -> None:
    """Navigate to /login, submit credentials, and wait for the home redirect.

    Raises RuntimeError if login does not complete within *timeout* seconds.
    """
    driver.get(f"{base_url}/login")

    wait = WebDriverWait(driver, timeout)

    user_input = wait.until(
        EC.presence_of_element_located((By.NAME, "user"))
    )
    user_input.clear()
    user_input.send_keys(username)

    pass_input = driver.find_element(By.NAME, "password")
    pass_input.clear()
    pass_input.send_keys(password)

    # Click the first submit button on the login form
    driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()

    # Wait until URL no longer contains /login (redirected to home)
    try:
        wait.until(EC.url_changes(f"{base_url}/login"))
    except Exception as exc:
        raise RuntimeError(
            f"Grafana login did not redirect after {timeout}s — "
            "check username/password in Settings."
        ) from exc


# ---------------------------------------------------------------------------
# Single-panel screenshot
# ---------------------------------------------------------------------------

def take_panel_screenshot(
    driver: webdriver.Chrome,
    base_url: str,
    dashboard_uid: str,
    panel_id: int,
    width: int = 800,
    height: int = 400,
) -> bytes:
    """Navigate to the d-solo panel URL and return a PNG screenshot as bytes.

    Sets the browser window to *width* x *height* before capturing so the
    panel fills the viewport. Waits 3 s after navigation for the panel to render.
    """
    url = (
        f"{base_url}/d-solo/{dashboard_uid}"
        f"?orgId=1&panelId={panel_id}&kiosk&theme=light"
    )
    driver.set_window_size(width, height)
    driver.get(url)
    time.sleep(3)
    return driver.get_screenshot_as_png()


# ---------------------------------------------------------------------------
# Batch capture
# ---------------------------------------------------------------------------

def capture_panels(
    dashboard_uid: str,
    panel_ids: list[int],
    grafana_settings: dict[str, str],
) -> dict[int, bytes]:
    """Screenshot every panel in *panel_ids* and return a panel_id → PNG bytes dict.

    Creates a single Chrome driver, logs in once, iterates panels, then closes
    the driver — even if errors occur.  Any panel that fails is stored as a
    plain white 800×400 "Panel unavailable" placeholder generated by Pillow.
    """
    base_url = grafana_settings.get("url", "").rstrip("/")
    username = grafana_settings.get("username", "")
    password = grafana_settings.get("password", "")

    results: dict[int, bytes] = {}
    driver: webdriver.Chrome | None = None

    try:
        driver = get_driver()
        login(driver, base_url, username, password)

        for panel_id in panel_ids:
            try:
                png = take_panel_screenshot(driver, base_url, dashboard_uid, panel_id)
                results[panel_id] = png
            except Exception:
                results[panel_id] = _unavailable_png()

    except Exception:
        # Login or driver creation failed — fill every panel with placeholder
        for panel_id in panel_ids:
            results.setdefault(panel_id, _unavailable_png())

    finally:
        if driver is not None:
            try:
                driver.quit()
            except Exception:
                pass

    return results


# ---------------------------------------------------------------------------
# Placeholder image
# ---------------------------------------------------------------------------

def _unavailable_png(width: int = 800, height: int = 400) -> bytes:
    """Return a plain white PNG with centred 'Panel unavailable' text via Pillow."""
    img = Image.new("RGB", (width, height), color=(255, 255, 255))
    draw = ImageDraw.Draw(img)

    text = "Panel unavailable"
    try:
        # Use a basic built-in font at a larger size if truetype is unavailable
        font = ImageFont.load_default()
    except Exception:
        font = None

    # Centre the text
    if font:
        bbox = draw.textbbox((0, 0), text, font=font)
        tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    else:
        tw, th = len(text) * 6, 11

    x = (width - tw) // 2
    y = (height - th) // 2
    draw.text((x, y), text, fill=(150, 150, 150), font=font)

    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()
